internal/providers/azure: add support for ssh keys
coreos/afterburn pull request #44
Opened 2017-05-19 23:53 UTC by dgonyeo

This PR adds support for fetching the user's ssh key in azure

Not ready for merge yet.

2017-06-01 12:32 UTC, lucab commented
I have to say I'm not super happy about having exec-wrappers around openssl and ssh-keygen and feeding them (plaintext) network input. Is there any reason for not using go crypto&codec primitives from stdlib?

2017-06-01 13:30 UTC, lucab requested changes

2017-06-01 13:30 UTC, lucab commented on internal/providers/azure/azure.go
> +	err := exec.ExecExpectZero("openssl", "req", "-x509", "-nodes", "-subj", "/CN=LinuxTransport", "-days", "32768", "-newkey", "rsa:2048", "-keyout", keyFilePath, "-out", certFilePath)
Are the common-name and expiration mandated somewhere? If so, please add a reference. If not, please use some meaningful cn and a shorter expiration (or leave a note why you are using such a large one, eg. early-boot time skews).

2017-06-02 18:02 UTC, dgonyeo commented on internal/providers/azure/azure.go
> +	err := exec.ExecExpectZero("openssl", "req", "-x509", "-nodes", "-subj", "/CN=LinuxTransport", "-days", "32768", "-newkey", "rsa:2048", "-keyout", keyFilePath, "-out", certFilePath)
I'm not sure if they're mandated, this command was directly copied from the waagent code: https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/common/utils/cryptutil.py#L30

I can play around with changing the CN and shortening the expiration, if it works with more reasonable values I'll change it to use them.

2017-06-02 18:08 UTC, dgonyeo commented
There isn't a strong reason for using exec-wrappers other than this is how the waagent works, and it took me less work to implement it here the same way it works in waagent than to work through how to do this in pure go. I wouldn't be opposed to spending the time on switching over to the golang stdlib, but I can't say how much time it would take me to figure that out.

2017-06-02 18:11 UTC, crawford commented
> it took me less work to implement it here the same way it works in waagent than to work through how to do this in pure go

I'm not interested in work being done unless it's being done correctly. Please investigate doing it properly.

2017-09-26 17:03 UTC, closed without merging