internal: Simplify checking for supported providers and metadata function to call
coreos/afterburn pull request #48
Opened 2017-06-01 01:33 UTC by joonas

This duplication bothered me a bit, so I figured I'd submit a PR to get rid of it.

2017-06-01 08:28 UTC, lucab commented
Perhaps a better suggestion here: introduce a `metadataFetcher() (fetchFn, error)` which returns the provider-specific fetcher or an error for unknown ones, then either react to the error or invoke the returned function. While at it, please also introduce some unit-test covering positive and negative cases.

2017-06-01 08:31 UTC, lucab requested changes

2017-06-01 08:31 UTC, lucab commented on internal/main.go
> +		metadataFn = openstackMetadata.FetchMetadata
I'd rather see this logic splits in its own testable function, bubbling-up errors. See the general comment for details.

2017-06-01 12:20 UTC, joonas commented
> Perhaps a better suggestion here: introduce a metadataFetcher(provider string) (fetchFn, error) which returns the provider-specific fetcher or an error for unknown ones, then either react to the error or invoke the returned function. While at it, please also introduce some unit-test covering positive and negative cases.

I went down this path also, but felt that it was more than I should introduce in one go. However, I'm happy to take a pass at implementing something like this if that'd be the preferred approach.

Thanks for the review!

2017-06-03 14:38 UTC, joonas commented
@lucab - is this in line with what you were thinking?

2017-06-05 17:35 UTC, cgonyeo approved these changes
LGTM (Luca is current on PTO)

2017-06-05 17:35 UTC, dgonyeo commented on internal/main.go
> +		return nil, errors.New("unknown provider")
This is a super tiny nit, but I prefer the pattern of doing a `var ErrUnknownProvider = ...` at the top of the file and returning it here. Makes it easier to expose known error values for tests and such.

2017-06-05 22:11 UTC, joonas commented on internal/main.go
> +		return nil, errors.New("unknown provider")
Totally makes sense, just did that 👍

2017-06-05 22:28 UTC, cgonyeo approved these changes
LGTM, rebase this on master and I'll merge

2017-06-05 22:38 UTC, joonas commented
Cool, should be good now 👍

2017-06-05 22:40 UTC, merged

2017-06-06 01:25 UTC, crawford commented on internal/main_test.go
> +			err:  errors.New("unknown provider"),
@dgonyeo the point of that refactor was to make use of it here.