providers: add vagrant_virtualbox provider
coreos/afterburn pull request #52
Opened 2017-06-30 17:41 UTC by AlexNPavel

This adds support for the vagrant_virtualbox provider (oem-id
vagrant-virtualbox) with variables VAGRANT_VIRTUALBOX_IPV4_PRIVATE
and VAGRANT_VIRTUALBOX_HOSTNAME

2017-06-30 18:03 UTC, cgonyeo requested changes
I'm not familiar with vagrant at all, is there a way for users to pass ssh keys that we'll want to support?

2017-06-30 18:03 UTC, dgonyeo commented on internal/providers/vagrant_virtualbox/vagrant_virtualbox.go
> +	for _, iface = range interfaces {
Why define `iface` earlier in the function? It doesn't appear to be used outside of this for loop, so just use a `:=` here.

2017-06-30 18:07 UTC, AlexNPavel commented
The only way for a user to pass in an ssh key is via the ignition config. There is also a vagrant specific way to replace the insecure key after ssh comes up, but we don't support that at the moment. Also, the way this metadata works is different since we don't read from a network host, we just read data from the system (which is why we need to configure everything via ignition first)

2017-06-30 18:12 UTC, cgonyeo approved these changes
LGTM, cc @crawford for design sanity-check of having all the metadata come from host introspection

2017-06-30 21:13 UTC, AlexNPavel commented
I added a bugfix that waits for eth1 to be ready and squash the commits. Look good @dgonyeo ?

2017-06-30 21:19 UTC, dgonyeo commented
Do you know if it's possible to configure a machine to not have a network interface? Is it possible that `eth1` would just never appear?

2017-06-30 21:22 UTC, AlexNPavel commented
With our Vagrantfile, there should always be an eth1. It would only not exist if someone removes that part of the Vagrantfile (in which case it would never appear)

2017-06-30 21:23 UTC, dgonyeo commented
That seems fine, even if they did that coreos-metadata with this commit will eventually still return successfully.

LGTM.

2017-06-30 21:24 UTC, merged

2017-08-31 01:14 UTC, crawford commented
@dgonyeo this didn't update the list of providers on the README.