internal/main.go: support for overriding metadata
coreos/afterburn pull request #55
Opened 2017-08-14 21:53 UTC by AlexNPavel

This adds the flag `set` which will set the specified attributes or
override the one's given by a provider.

2017-08-14 22:32 UTC, bgilbert requested changes
@crawford @dgonyeo, thoughts on whether this is a good idea?  The motivator is to allow Vagrant to generate its own attributes (e.g. private IP address) that will be merged into whatever coreos-metadata produces on its own.

2017-08-14 22:32 UTC, bgilbert commented on internal/main.go
> +	flag.Var(&flags.overrides, "set", "Set an environment variable, overriding the default/detected variable")
- Should be in alphabetical order.
- The `attributes` help text calls them `metadata attributes`, so we should be consistent here.
- The help text should make clear that a key=value pair is wanted and that the option can be specified multiple times.

2017-08-14 22:32 UTC, bgilbert commented on internal/main.go
> +		fmt.Println("Could not split override set correctly")
This is potentially a user-visible error message and should clearly describe the problem.

2017-08-14 22:32 UTC, bgilbert commented on internal/main.go
> +		return nil
Don't we want to fail in this case?

2017-08-14 22:32 UTC, bgilbert commented on internal/main.go
> +	vals := strings.Split(v, "=")
Values should be allowed to contain `=`, so this should be a `SplitN`.

2017-08-14 22:40 UTC, dgonyeo commented
A couple questions:
- How would this be used? Would the user have to add a systemd drop-in to add the arguments to coreos-metadata via an environment variable or something?
- If this is vagrant specific, why not put the logic for getting information about the environment into a vagrant provider and have coreos-metadata run normally, instead of entering in the information on the command line only to be spit back out?

2017-08-14 22:47 UTC, bgilbert commented
1. Yes.
2. We're trying to get rid of the Vagrant-specific OEMs (and just use e.g. the `virtualbox` and `vmware` OEMs), since the Vagrant-specific ones conflate the virtualization environment with the tool driving it.  The generic OEMs can't know when they should e.g. wait for a second NIC to come up, and it seems too hacky to e.g. add a `-vagrant` option which causes special behavior in particular OEMs.

This would also allow kola to inject public and private IPs for ESX, assuming coreos-metadata gained a vmware OEM (which may or may not make sense).

2017-08-14 23:43 UTC, bgilbert commented
Still missing the last two comments from https://github.com/coreos/coreos-metadata/pull/55#discussion_r133076632.

2017-08-15 00:09 UTC, bgilbert commented on internal/main.go
> +	flag.Var(&flags.overrides, "set", "Set a metadata attribute, potentially overriding the attribute given by a provider. This flag can be specified multiple times and expects a key=value pair. Eg: VIR
tiny nit: should be `e.g.`

2017-08-15 00:09 UTC, bgilbert commented on internal/main.go
> +		return fmt.Errorf("Incorrectly formatted -set argument: %s", v)
I get:

```
$ bin/coreos-metadata -set foo
Incorrectly formatted -set argument: foo
invalid value "foo" for flag -set: Incorrectly formatted -set argument: foo
Usage of bin/coreos-metadata:
[...]
```

2017-08-16 00:54 UTC, bgilbert commented
Discussed with @dgonyeo offline.  To avoid Vagrant etc. having to inject systemd dropins, the proposed approach is now to have coreos-metadata walk one or more directories containing files with key=value pairs, where the directory paths are possibly provided via command-line options.

2017-09-26 17:03 UTC, closed without merging