providers: rename vagrant-virtualbox to virtualbox
coreos/afterburn pull request #56
Opened 2017-08-14 22:44 UTC by AlexNPavel

This allows us to avoid using specific oem-ids for vagrant provisioned
machines and use more ids

2017-08-14 22:54 UTC, cgonyeo requested changes

2017-08-14 22:54 UTC, dgonyeo commented on internal/main.go
> +	case "virtualbox":
Can you also add `"vagrant-virtualbox"` to this line? Otherwise won't coreos-metadata will stop working for users when they upgrade to this version?

2017-08-16 00:07 UTC, bgilbert commented on README.md
> +      - COREOS_VIRTUALBOX_IPV4 (only via vagrant)
Will we want to distinguish between public and private IPv4?

2017-08-16 00:07 UTC, bgilbert commented on internal/main.go
> +	case "virtualbox", "vagrant-virtualbox":
Needs a comment explaining the second arm.

2017-08-17 20:32 UTC, crawford commented on README.md
> +      - COREOS_VIRTUALBOX_IPV4 (only via vagrant)
What happens if there are multiple network interfaces?

2017-08-17 20:42 UTC, AlexNPavel commented on README.md
> +      - COREOS_VIRTUALBOX_IPV4 (only via vagrant)
@crawford I meant that to be the private ipv4. Fixed

2017-08-17 21:04 UTC, crawford commented on README.md
> +      - COREOS_VIRTUALBOX_IPV4_PRIVATE (only via vagrant)
> only via vagrant

This alone seems to indicate that the platform should incorporate both virtualbox and vagrant.

2017-10-20 17:39 UTC, sdemos commented
there doesn't seem to be consensus on this rename, and it is now stale. if we still consider this a problem with the rust rewrite, we should open a new pr.

2017-10-20 17:39 UTC, closed without merging

2017-10-20 20:07 UTC, bgilbert commented
There is a consensus, I just haven't written it up or implemented it.  I'll reopen on the other project.